apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resnet-data-pvc
  namespace: kubeflow
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resnet-ckpt-pvc
  namespace: kubeflow
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
